openapi: 3.0.0
info:
  title: Online shop API
  description: An API to access data of an online shop. Use this API if you want
    to retrieve shop policies, such as return policies. Also use this API if you
    want to retrieve customer and order data, including returns, as well as if
    you need to change an order, such as initiate a return.
  version: 1.0.0
paths:
  /orders:
    get:
      summary: Get all orders for a customer
      operationId: getAllOrders
      tags:
        - Orders
      description: Fetches a list of all orders placed within the system, providing
        essential details such as order ID, the date the order was placed, and
        the total amount of the order. This endpoint is indispensable for order
        tracking, management, and analysis, offering a bird's-eye view of all
        transactions. The user ID will be passed to this tool in a secure
        manner, so it doesn't need to be asked.
      parameters: []
      responses:
        "200":
          description: Successfully retrieves a list of orders, each encapsulated with an
            order ID, order date, and total amount. This comprehensive overview
            aids in order tracking, financial calculations, and logistical
            planning.
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      type: object
                      properties:
                        orderId:
                          type: string
                          description: A unique identifier for each order. This ID is crucial for
                            tracking, referencing, and managing orders
                            throughout their lifecycle.
                        orderDate:
                          type: string
                          format: date-time
                          description: The exact date and time when the order was placed. This timestamp
                            is vital for chronological ordering, analysis, and
                            understanding order patterns over time.
                        total:
                          type: number
                          format: float
                          description: The total monetary amount of the order. This value is important for
                            financial reporting, budgeting, and calculating the
                            overall revenue generated by sales.
  /policies:
    get:
      summary: Get the shop policies
      operationId: getPolicies
      tags:
        - Policies
      description: Fetches all policies that concern customers. Currently only for
        returns policy.
      responses:
        "200":
          description: Successfully retrieves all relevant policies.
          content:
            application/json:
              schema:
                type: object
                properties:
                  returns:
                    type: string
                    description: A natural language description of the returns policy
